# Generated by Django 5.1.4 on 2025-01-13 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChristmasListIndex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('link', models.URLField(max_length=300)),
                ('purchased', models.BooleanField()),
                ('suggested_amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
