# Generated by Django 5.1.4 on 2025-01-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChristmasListIndex', '0002_giftidea_delete_geeksmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftidea',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='giftidea',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
