# Generated by Django 5.1.4 on 2025-01-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChristmasListIndex', '0003_alter_giftidea_link_alter_giftidea_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftidea',
            name='created_on',
        ),
        migrations.AddField(
            model_name='giftidea',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
